### ISSUE TITLE
PHP exception: could not find driver

### ISSUE THREAD

**Issue by christophwischow** [kiwiz/411#8]
Hey,

i can't get this issue solved while trying to install 411.

```
core@ubuntu:/var/www$ 411/bin/create_site.php 
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/411/phplib/DB.php:49
Stack trace:
#0 /var/www/411/phplib/DB.php(49): PDO->__construct('sqlite:/var/www...', 'root', NULL, Array)
#1 /var/www/411/phplib/DB.php(35): FOO\DB::connect('sqlite:/var/www...', 'root', NULL)
#2 /var/www/411/phplib/411bootstrap.php(62): FOO\DB::init()
#3 /var/www/411/bin/create_site.php(7): require_once('/var/www/411/ph...')
#4 {main}
  thrown in /var/www/411/phplib/DB.php on line 49
```

**Comment by christophwischow** [comment]
Problem solved:

I missed the following package to connect php to sqlite.

to get it:
`sudo apt-get install php5-sqlite`
